#!/usr/bin/env python
"""
Newsgroup post classification

References
----------
https://scikit-learn.org/stable/datasets/index.html#loading-other-datasets

__author__ = "Hide Inada"
__copyright__ = "Copyright 2018, Hide Inada"
__license__ = "The MIT License"
__email__ = "hideyuki@gmail.com"
"""

import os
import logging
import argparse
import sys
from pathlib import Path
import tensorflow as tf
import numpy as np
import keras

from sklearn.datasets.base import Bunch
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics

from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense

from project.load_text_data import load_text_from_files
from project.text_to_index import map_label_to_index
from project.text_to_index import map_text_list_to_word_list
from project.text_to_index import map_text_to_token_matrix
from project.text_to_index import map_word_list_to_vocabulary

log = logging.getLogger(__name__)
logging.basicConfig(level=os.environ.get("LOGLEVEL", "INFO"))  # Change the 2nd arg to INFO to suppress debug logging

EPOCH_SIZE = 20
TOP_VOCABULARY_SIZE = 10000

# Example of data dir:
# ../../../../ai/dataset/20/20newsgroups_fromto_only/20news-18828
# Specify this with --data_dir option on the command line

def example(data_dir=None):
    """Train the model and predict.

    Parameters
    ----------
    data_dir: str
        Directory where the data is stored.

    raises
    -------
    ValueError
        If data_dir is not set.
    """
    if data_dir is None:
        raise ValueError("data_dir is not set.")

    # Load text data
    (x_train_text, y_train_labels), (x_test_text, y_test_labels) = \
        load_text_from_files(Path(data_dir), test_dataset_ratio=0.2, errors='ignore')

    num_files_train = len(x_train_text)
    num_labels_train = len(set(y_train_labels))

    num_files_test = len(x_test_text)
    num_labels_test = len(set(y_test_labels))

    log.info("Number of labels found in training dataset: %d" % (num_labels_train))
    log.info("Number of posts found in training dataset: %d" % (num_files_train))

    log.info("Number of labels found in test dataset: %d" % (num_labels_test))
    log.info("Number of posts found in test dataset: %d" % (num_files_test))

    bunch_train =  Bunch(data=x_train_text, target=y_train_labels)
    bunch_test =  Bunch(data=x_test_text, target=y_test_labels)

    vectorizer = TfidfVectorizer()
    vectorizer.fit(bunch_train.data)
    vectors_train = vectorizer.transform(bunch_train.data)

    vectors_test = vectorizer.transform(bunch_test.data)

    clf = MultinomialNB(alpha=.01)
    clf.fit(vectors_train, bunch_train.target)
    MultinomialNB(alpha=0.01, class_prior=None, fit_prior=True)

    y_hat_test = clf.predict(vectors_test)  # y_hat contains list of string labels
    metrics.f1_score(bunch_test.target, y_hat_test, average='macro')

    # Test against test dataset

    total_size = y_hat_test.shape[0]
    y_test = np.array(y_test_labels)

    matched_indices = (y_hat_test == y_test)
    #matched_count = y_test_labels[matched_indices].shape[0]

    matched_array = y_test[matched_indices]
    matched_count = matched_array.shape[0]
    log.info(
         "Matched: %d out of Total: %d (%f percent)" % (matched_count, total_size, matched_count * 100 / total_size))


def main():
    """Defines an application's main functionality"""

    parser = argparse.ArgumentParser(description='Newsgroup post classifier')
    parser.add_argument('--data_dir',
                        type=str,
                        help="Data directory")

    args = parser.parse_args()
    data_dir = args.data_dir

    example(data_dir = data_dir)


if __name__ == "__main__":
    main()
