#!/usr/bin/env python
"""
Reuter_50_50 Dataset classification using bigrams.

References
----------
https://archive.ics.uci.edu/ml/datasets/Reuter_50_50#
https://scikit-learn.org/stable/datasets/id.html#loading-other-datasets
https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html
https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.MultinomialNB.html

__author__ = "Hide Inada"
__copyright__ = "Copyright 2018, Hide Inada"
__license__ = "The MIT License"
__email__ = "hideyuki@gmail.com"
"""

import os
import logging
import argparse
import sys
from pathlib import Path
import numpy as np

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics

from project.load_text_data import load_text_and_label_id_from_training_and_test_dirs

log = logging.getLogger(__name__)
logging.basicConfig(level=os.environ.get("LOGLEVEL", "INFO"))  # Change the 2nd arg to INFO to suppress debug logging


# Example of training dataset dir:
# ../../../../ai/dataset/reuters50/C50train
# ../../../../ai/dataset/reuters50/C50test

# Specify this with --train_data_dir and --test_data_dir option on the command line

def example(train_data_dir=None, test_data_dir=None):
    """Train the model and predict.

    Parameters
    ----------
    train_data_dir: str
        Directory where the training dataset is stored.
    test_data_dir: str
        Directory where the test dataset is stored.

    raises
    -------
    ValueError
        If train_data_dir or test_data_dir is not set.
    """
    if train_data_dir is None:
        raise ValueError("train_data_dir is not set.")

    if test_data_dir is None:
        raise ValueError("test_data_dir is not set.")

    # Load text data
    (x_train_text, y_train_id), (x_test_text, y_test_id), (label_to_id, id_to_label) = \
        load_text_and_label_id_from_training_and_test_dirs(Path(train_data_dir), Path(test_data_dir))

    num_files_train = len(x_train_text)
    num_labels_train = len(set(y_train_id))

    num_files_test = len(x_test_text)
    num_labels_test = len(set(y_test_id))

    log.info("Number of labels found in training dataset: %d" % (num_labels_train))
    log.info("Number of posts found in training dataset: %d" % (num_files_train))

    log.info("Number of labels found in test dataset: %d" % (num_labels_test))
    log.info("Number of posts found in test dataset: %d" % (num_files_test))

    tfid = Pipeline([
        ('vect', CountVectorizer(ngram_range=(1, 3))), # select trigrams (min 1 word, max 3 words)
        ('tfidf', TfidfTransformer())
    ])

    x_train_vectors = tfid.fit_transform(x_train_text)  # Convert training dataset to tfid matrix
    x_test_vectors = tfid.transform(x_test_text)  # Convert test set to tfid matrix

    classifier = MultinomialNB(
        alpha=.01)  # Naive Bayes classifier, per doc alpha accounts for features missing in training samples
    classifier.fit(x_train_vectors, y_train_id)

    y_hat_test = classifier.predict(x_test_vectors)  # y_hat contains list of string labels
    metrics.f1_score(y_test_id, y_hat_test, average='macro')

    # Test against test dataset
    total_size = y_hat_test.shape[0]
    y_test = y_test_id

    matched_indices = (y_hat_test == y_test)

    matched_array = y_test[matched_indices]
    matched_count = matched_array.shape[0]
    log.info(
        "Matched: %d out of Total: %d (%f percent)" % (matched_count, total_size, matched_count * 100 / total_size))


def main():
    """Defines an application's main functionality"""

    parser = argparse.ArgumentParser(description='Reuter 50 news author classifier')
    parser.add_argument('--train_data_dir',
                        type=str,
                        default="../../../../ai/dataset/reuters50/C50train",
                        help="Training dataset directory")
    parser.add_argument('--test_data_dir',
                        type=str,
                        default="../../../../ai/dataset/reuters50/C50test",
                        help="Test dataset directory")
    args = parser.parse_args()
    train_data_dir = args.train_data_dir
    test_data_dir = args.test_data_dir

    example(train_data_dir=train_data_dir, test_data_dir=test_data_dir)


if __name__ == "__main__":
    main()
