#!/usr/bin/env python
"""
Train word2vec model to be used for Newsgroup post classification using embedding

__author__ = "Hide Inada"
__copyright__ = "Copyright 2018, Hide Inada"
__license__ = "The MIT License"
__email__ = "hideyuki@gmail.com"
"""

import os
import logging
import argparse

from pathlib import Path
import numpy as np
from gensim.models.word2vec import Word2Vec

from project.load_text_data import load_text_from_files
from project.text_to_id import map_label_to_id
from project.text_to_id import map_text_list_to_word_list
from project.text_to_id import map_text_to_word_id
from project.text_to_id import map_word_list_to_vocabulary


MODEL_PATH = "/tmp/tp/word2vec_example.model"

log = logging.getLogger(__name__)
logging.basicConfig(level=os.environ.get("LOGLEVEL", "INFO"))  # Change the 2nd arg to INFO to suppress debug logging

# Example of data dir:
# ../../../../ai/dataset/20/20newsgroups_fromto_only/20news-18828
# Specify this with --data_dir option on the command line

def train(data_dir=None):
    """Train the model.

    Parameters
    ----------
    data_dir: str
        Directory where the data is stored.

    raises
    -------
    ValueError
        If data_dir is not set.
    """
    if data_dir is None:
        raise ValueError("data_dir is not set.")

    # Load text data
    (x_train_text, y_train_labels), (x_test_text, y_test_labels) = \
        load_text_from_files(Path(data_dir), test_dataset_ratio=0.2, errors='ignore')

    num_files_train = len(x_train_text)
    num_labels_train = len(set(y_train_labels))

    num_files_test = len(x_test_text)
    num_labels_test = len(set(y_test_labels))

    log.info("Number of labels found in training dataset: %d" % (num_labels_train))
    log.info("Number of posts found in training dataset: %d" % (num_files_train))

    log.info("Number of labels found in test dataset: %d" % (num_labels_test))
    log.info("Number of posts found in test dataset: %d" % (num_files_test))

    assert num_labels_train == num_labels_test

    # Break up entire text to words
    all_words = map_text_list_to_word_list(x_train_text)

    model = Word2Vec([all_words],
                     size=5,  # Number of dimension for a word vector
                     window=5,
                     min_count=1,
                     workers=4)  # Num threads

    model.save(MODEL_PATH)

def main():
    """Defines an application's main functionality"""

    parser = argparse.ArgumentParser(description='Newsgroup post classifier')
    parser.add_argument('--data_dir',
                        type=str,
                        help="Data directory")

    args = parser.parse_args()
    data_dir = args.data_dir

    train(data_dir=data_dir)


if __name__ == "__main__":
    main()
